routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

## Controllers LandingPage
Route::get('/about-us', 'LandingPageController@about')->name('about');
Route::get('/links-interest', 'LandingPageController@links')->name('links');
Route::get('/videos-interest', 'LandingPageController@videos')->name('videos');

## Controllers Store
Route::get('store/category', 'StoreProductsController@storeCategory')->name('store.category');
Route::get('store/payment_methods', 'StoreProductsController@paymentMethods')->name('payment_methods');
Route::get('store/{category}/products', 'StoreProductsController@store')->name('store');
Route::get('store/{category}', 'StoreProductsController@storeProducts')->name('store.products');
Route::get('store/products/offers', 'StoreProductsController@offers')->name('offers');
Route::get('offers/products', 'StoreProductsController@offersProducts')->name('offers.products');
Route::get('store/product/{product}', 'StoreProductsController@product')->name('store.product');

## Controller News in LandingPage
Route::get('articles', 'ArticlesController@index')->name('articles.index');
Route::get('articles/blins', 'ArticlesController@articles')->name('articles');
Route::get('articles/{article}', 'ArticlesController@singleArticle')->name('articles.single-article');

## Controller LaborBag
Route::get('labor-bag', 'BagsController@index')->name('bags.index');
Route::get('bags', 'BagsController@bags')->name('bags');
Route::get('bags/{work}', 'BagsController@create')->name('bags.create');
Route::post('bags', 'BagsController@store')->name('bags.store');

## Controller Cart
Route::get('cart/show', 'CartController@show')->name('cart.show');
Route::get('cart/add/{product}', 'CartController@add')->name('cart.add');
Route::get('cart/delete/{product}', 'CartController@delete')->name('cart.delete');
Route::get('cart/trash', 'CartController@trash')->name('cart.trash');
Route::get('cart/update/{product}/{quantity}', 'CartController@update')->name('cart.update');

## Controllers Messages
Route::get('message', 'ContactController@create')->name('message.create');
Route::post('message', 'ContactController@store')->name('message.store');

## Controllers Auth Guest
Route::namespace('Auth')->middleware(['web', 'guest'])->group(function () {
	## @Login
	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	## @Reset Password
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	## @Register
	Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
	Route::post('register', 'RegisterController@register');
	## @Validate
	//Route::get('account/confirm_account/{token_confirmed}', 'ValidateEmailController@validateTokenEmail')->name('confirm_account');
});

Route::namespace('Auth')->middleware(['web'])->group(function () {
	## @Logout
	Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::middleware(['auth', 'web'])->group(function () {
	## @Cart
	Route::get('order-detail', 'CartController@orderDetail')->name('order.detail');

	## @Payment PayPal
	Route::get('payment', 'PaypalController@postPayment')->name('payment');
	Route::get('payment/status', 'PaypalController@getPaymentStatus')->name('payment.status');
});

## Controllers Middleware Auth, Admin
Route::middleware(['auth', 'authPermission'])->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');

	Route::get('feature/{id}/delete', 'ProductsController@destroyFeature')->name('delete.feature');

	Route::get('profile', 'ProfileController@index')->name('profile.index');
	Route::post('profile', 'ProfileController@store')->name('profile.store');

	Route::get('dataTable/categories', 'CategoriesController@dataTable')->name('dataTable.categories');
	Route::get('dataTable/messages', 'MessagesController@dataTable')->name('dataTable.messages');
	Route::get('dataTable/works', 'WorksController@dataTable')->name('dataTable.works');
	Route::get('dataTable/products', 'ProductsController@dataTable')->name('dataTable.products');
	Route::get('dataTable/news', 'NewsController@dataTable')->name('dataTable.news');
	Route::get('dataTable/links', 'LinksController@dataTable')->name('dataTable.links');
	Route::get('dataTable/videos', 'VideosController@dataTable')->name('dataTable.videos');
	Route::get('dataTable/users', 'UsersController@dataTable')->name('dataTable.users');
	Route::get('dataTable/postulates', 'PostulatesController@dataTable')->name('dataTable.postulates');

	Route::get('postulates/{id}/download', 'PostulatesController@download')->name('download.postulates');
	Route::get('products/{product}/gallery', 'ProductsController@gallery')->name('products.gallery');

	Route::post('categories/{category}/update', 'CategoriesController@update')->name('categories.update');
	Route::post('products/{product}/update', 'ProductsController@update')->name('products.update');
	Route::post('works/{work}/update', 'WorksController@update')->name('works.update');

	Route::resource('messages', 'MessagesController');
	Route::resource('works', 'WorksController', ['except' => ['update']]);
	Route::resource('news', 'NewsController');
	Route::resource('users', 'UsersController');
	Route::resource('videos', 'VideosController');
	Route::resource('postulates', 'PostulatesController');
	Route::resource('categories', 'CategoriesController', ['except' => ['update']]);
	Route::resource('products', 'ProductsController', ['except' => ['update']]);
	Route::resource('links', 'LinksController');
});

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NewsUpdateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Article;
use Storage;
class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('news.index');
    }

    public function dataTable(Request $request)
    {
        $news = Article::with('user')->orderBy('id', 'DESC')->paginate(10);

        return [
            'pagination' => [
                'total'        => $news->total(),
                'current_page' => $news->currentPage(),
                'per_page'     => $news->perPage(),
                'last_page'    => $news->lastPage(),
                'from'         => $news->firstItem(),
                'to'           => $news->lastPage(),
            ],
            'news' => $news
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news.create');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validatorArray(array $data)
    {
        return Validator::make($data, [
            'title' => 'required|unique:news|max:175',
            'image' => 'required|image',
            'date_ini' => 'required',
            'date_end' => 'required'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validatorArray($request->all())->validate();
        $imageName = $request->file('image')->store('news', 'public');
        $new = new Article();
        $new->user_ui = $request->user()->id;
        $new->title = $request['title'];
        $new->slug = $this->replace($request['title']);
        $new->detail = $request['detail'];
        $new->date_ini = $request['date_ini'];
        $new->date_end = $request['date_end'];
        $new->image = $imageName;
        $new->save();

        return redirect('/news')->with(session()->flash('success', 'La noticia ' . $new->title . ' ha sido agregada.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::with('images')->whereSlug($id)->firstOrFail();

        return view('news.edit')->with(['article' => $article]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Validation\Validator
     */
    public function update(NewsUpdateRequest $request, $id)
    {
        $new = Article::with('images')->whereSlug($id)->firstOrFail();
        $imageName = $request->file('image')->store('news', 'public');
        $new->title = $request['title'];
        $new->slug = $this->replace($request['title']);
        $new->detail = $request['detail'];
        $new->date_ini = $request['date_ini'];
        $new->date_end = $request['date_end'];
        $new->image = $imageName;
        $new->save();

        return redirect('/news')->with(session()->flash('success', 'La noticia ' . $new->title . ' ha sido editada.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $new = Article::whereSlug($id)->firstOrFail();
        $new->delete();

        $request->session()->flash('success', 'La noticia ' . $new->title . ' ha sido borrada.');

        return response()->json($array);
    }
}

resources/views/news/create.blade.php
@extends('layouts.dashboard')

@section('breadcrumbs', 'Añadir noticia')

@section('content')

<div class="row justify-content-center">
	<div class="col-xl-8 order-xl-1">
		<div class="card bg-secondary shadow">
			<div class="card-header bg-white border-0">
				<div class="row align-items-center">
					<div class="col-8">
						<h3 class="mb-0">Nuevo artículo</h3>
					</div>
				</div>
			</div>
            <div class="card-body">
                <form ref="form" id="createform" action="{{ route('news.store') }}" novalidate enctype="multipart/form-data" method="POST" autocomplete="off">
                    @csrf
                    <h6 class="heading-small mb-4">Información de artículo</h6>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-md-12">
                                <label class="form-control-label" for="input-title">Título</label>
                                  <div class="form-group {{ $errors->has('title') ? 'has-danger' : '' }}">
                                    <input
                                        type="text"
                                        id="input-title"
                                        name="title"
                                        class="form-control {{ $errors->has('title') ? 'has-danger' : '' }}"
                                        placeholder="Blins"
                                        value="{{ old('title') }}"
                                        required/>
                                      @if ($errors->has('title'))
                                          <span class="text-danger">{{ $errors->first('title') }}</span>
                                      @endif
                                  </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="form-control-label" for="input-date_ini">Fecha Inicio</label>
                                <div class="form-group @if($errors->has('date_ini')) has-danger @endif">
                                    <input type="date" id="input-date_ini" name="date_ini" class="form-control @if($errors->has('date_ini')) is-invalid @endif" required/>
                                    @if ($errors->has('date_ini'))
                                          <span class="text-danger">{{ $errors->first('date_ini') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label class="form-control-label" for="input-date_end">Fecha Final</label>
                                <div class="form-group @if($errors->has('date_end')) has-danger @endif">
                                    <input type="date" id="input-date_end" name="date_end" class="form-control @if($errors->has('date_end')) is-invalid @endif" required/>
                                    @if ($errors->has('date_end'))
                                          <span class="text-danger">{{ $errors->first('date_end') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <label class="form-control-label" for="detail">Detalles</label>
                          <div class="form-group {{ $errors->has('detail') ? 'has-danger' : '' }}">
                               <textarea
                                   rows="4"
                                   id="detail"
                                   name="detail"
                                   class="form-control {{ $errors->has('detail') ? 'has-danger' : '' }}"
                                   placeholder="Características del artículo ...">
                                   {{ old('detail') }}
                               </textarea>
                              @if ($errors->has('detail'))
                                  <span class="text-danger">{{ $errors->first('detail') }}</span>
                              @endif
                          </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="form-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="image">
                                <label class="custom-file-label" for="customFile">Choose file</label>
                                @if ($errors->has('image'))
                                    <span class="text-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
		</div>
	</div>
</div>

@endsection

resources/views/news/edit.blade.php
@extends('layouts.dashboard')

@section('breadcrumbs', 'Editar noticias')

@section('content')

<div class="row justify-content-center">
	<div class="col-xl-8 order-xl-1">
		<div class="card bg-secondary shadow">
			<div class="card-header bg-white border-0">
				<div class="row align-items-center">
					<div class="col-8">
						<h3 class="mb-0">Editar noticia</h3>
					</div>
				</div>
			</div>
			{{--<edit-news :article="{{ $new }}" :http="'{{ route('news.update', $new) }}'"></edit-news>--}}
            <div class="card-body">
                <form ref="form" id="createform" action="{{ route('news.update', $article) }}" novalidate enctype="multipart/form-data" method="POST" autocomplete="off">
                    @method('PUT')
                    @csrf
                    <h6 class="heading-small mb-4">Información de artículo</h6>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-md-12">
                                <label class="form-control-label" for="input-title">Título</label>
                                <div class="form-group {{ $errors->has('title') ? 'has-danger' : '' }}">
                                    <input
                                        type="text"
                                        id="input-title"
                                        name="title"
                                        class="form-control {{ $errors->has('title') ? 'has-danger' : '' }}"
                                        placeholder="Blins"
                                        value="{{ $article->title }}"
                                        required/>
                                    @if ($errors->has('title'))
                                        <span class="text-danger">{{ $errors->first('title') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="form-control-label" for="input-date_ini">Fecha Inicio</label>
                                <div class="form-group @if($errors->has('date_ini')) has-danger @endif">
                                    <input type="date" id="input-date_ini" name="date_ini" value="{{ $article->date_ini }}" class="form-control @if($errors->has('date_ini')) is-invalid @endif" required/>
                                    @if ($errors->has('date_ini'))
                                          <span class="text-danger">{{ $errors->first('date_ini') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label class="form-control-label" for="input-date_end">Fecha Final</label>
                                <div class="form-group @if($errors->has('date_end')) has-danger @endif">
                                    <input type="date" id="input-date_end" name="date_end" value="{{ $article->date_end }}" class="form-control @if($errors->has('date_end')) is-invalid @endif" required/>
                                    @if ($errors->has('date_end'))
                                          <span class="text-danger">{{ $errors->first('date_end') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <label class="form-control-label" for="detail">Detalles</label>
                        <div class="form-group {{ $errors->has('detail') ? 'has-danger' : '' }}">
                            <textarea
                                rows="4"
                                id="detail"
                                name="detail"
                                class="form-control {{ $errors->has('detail') ? 'has-danger' : '' }}"
                                placeholder="Características del artículo ...">
                                {{ $article->detail }}
                            </textarea>
                            @if ($errors->has('detail'))
                                <span class="text-danger">{{ $errors->first('detail') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="form-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="image">
                                <label class="custom-file-label" for="customFile">Choose file</label>
                                @if ($errors->has('image'))
                                    <span class="text-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="pl-lg-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
		</div>
	</div>
</div>

@endsection

resources/views/news/index.blade.php
@extends('layouts.dashboard')

@section('breadcrumbs', 'Noticias')

@section('content')

<!-- Table -->
<div class="row">
	<div class="col">

		@include('errors.messages')
		
		<div class="card shadow">
			<div class="card-header border-0">
				<div class="row align-items-center">
					<div class="col-8">
						<h3 class="mb-0">Noticias</h3>
					</div>
					<div class="col-4 text-right">
						<a href="{{ route('news.create') }}" class="btn btn-sm btn-primary">NUEVA NOTICIA</a>
					</div>
				</div>
			</div>
			<table-news></table-news>
		</div>
	</div>
</div>

@endsection